version: '3.1'

services:
  attacker:
    tty: true
    build: ./attacker/
    container_name: attacker
    depends_on:
      - server
    expose:
      - 8998
    networks:
      - network

  server:
    tty: true
    build: ./server/
    container_name: server
    expose:
      - 8080
    networks:
      - network

networks:
  network:
    driver: bridge

